<?php
$root=dirname(__DIR__);$fail=[];$assert=static function(bool $ok,string $message)use(&$fail){if(!$ok)$fail[]=$message;};
$migration=(string)file_get_contents($root.'/database/migrations/2026-08-14-admin-product-editor-v2.sql');
$catalogMigration=(string)file_get_contents($root.'/database/migrations/2026-08-15-catalog-product-fields.sql');
$cleanupMigration=(string)file_get_contents($root.'/database/migrations/2026-08-16-remove-obsolete-product-fields.sql');
$unitMigration=(string)file_get_contents($root.'/database/migrations/2026-08-27-category-default-unit-type.sql');
$schema=(string)file_get_contents($root.'/database/schema.sql');
$setup=(string)file_get_contents($root.'/database/setup.php');
$categoryHelper=(string)file_get_contents($root.'/includes/helpers/site-settings.php');
$categoryAdmin=(string)file_get_contents($root.'/admin/categories.php');
$categoryService=(string)file_get_contents($root.'/includes/services/CategoryAdminService.php');
$cron=(string)file_get_contents($root.'/cron/run-plugins.php');
$service=(string)file_get_contents($root.'/includes/services/ProductAdminService.php');
$editor=(string)file_get_contents($root.'/admin/edit-fabric.php');
$adminScript=(string)file_get_contents($root.'/js/admin.js');
$editorScript=(string)file_get_contents($root.'/admin/partials/fabric-product-form-script.php');
$editorForm=(string)file_get_contents($root.'/admin/partials/fabric-product-form.php');
$media=(string)file_get_contents($root.'/admin/product-media.php');
$fabric=(string)file_get_contents($root.'/fabric.php');
$order=(string)file_get_contents($root.'/place-order.php');
$orderSnapshot=(string)file_get_contents($root.'/includes/services/OrderItemSnapshotService.php');
$parcel=(string)file_get_contents($root.'/plugins/shipping-courier/modules/bigship-payloads.php');
require_once $root.'/includes/services/ProductAdminService.php';
require_once $root.'/includes/services/CartService.php';
$assert(str_contains($migration,"ENUM('draft','active','inactive')")&&str_contains($migration,'fabric_media'),'Draft status or gallery migration missing.');
$assert(str_contains($migration,'CREATE UNIQUE INDEX uq_fabrics_slug')&&str_contains($migration,'product_type'),'Slug uniqueness or product type migration missing.');
$assert(str_contains($service,'function readiness')&&str_contains($service,'function publish')&&str_contains($service,'function createDraft'),'Shared draft/readiness/publish service contract missing.');
$assert(str_contains($service,'skuAvailable')&&str_contains($service,'uniqueSlug'),'Stable unique SKU/slug validation missing.');
$assert(str_contains($editor,'check-readiness-btn')&&str_contains($editor,'product-media-upload')&&str_contains($editorScript,'beforeunload'),'Editor readiness, media, or unsaved warning missing.');
$assert(str_contains($media,"\$action==='reorder'")&&str_contains($media,"\$action==='delete'")&&str_contains($media,'syncLegacyMedia'),'Transactional gallery compatibility actions missing.');
$assert(str_contains($fabric,"\$_GET['slug']")&&str_contains($fabric,"header('Location: ' . \$target, true, 301)")&&str_contains($fabric,'$metaTitle'),'Clean storefront slug/redirect/SEO behavior missing.');
$assert(str_contains($orderSnapshot,'effective_gst_rate')&&str_contains($orderSnapshot,'effective_hsn_code')&&str_contains($order,'OrderItemSnapshotService::build'),'Per-product tax snapshots missing.');
$assert(str_contains($parcel,"\$item['shipping_weight_kg']")&&str_contains($parcel,"\$item['parcel_length_cm']"),'Per-product parcel overrides missing.');
$assert(str_contains($catalogMigration,'product_code')&&str_contains($catalogMigration,'amazon_asin')&&str_contains($catalogMigration,'catalog_data'),'Catalogue field migration missing.');
$assert(str_contains($cleanupMigration,'DROP COLUMN material')&&str_contains($cleanupMigration,'DROP COLUMN price_inr')&&str_contains($cleanupMigration,'INSERT INTO fabric_media'),'Obsolete product field cleanup migration missing or unsafe.');
$assert(str_contains($service,'self::categoryDefaultUnitType($conn, $category)'),'Draft creation must load the category-specific selling unit in the service.');
$assert(ProductAdminService::normalizeDraftUnitType('piece','meter')==='meter','A category default must override the submitted draft unit.');
$assert(ProductAdminService::normalizeDraftUnitType('piece','')==='piece','Categories without a default must retain the selected unit.');
$assert(str_contains($unitMigration,"COLUMN_NAME = 'default_unit_type'")&&str_contains($unitMigration,"slug = 'fabric-by-meter'")&&!str_contains($unitMigration,'UPDATE fabrics'),'The category unit migration must be idempotent and must not rewrite existing products.');
foreach([$schema,$setup] as $categorySchemaSource)$assert(str_contains($categorySchemaSource,"default_unit_type ENUM('meter','piece','set')"),'Fresh schema and setup must define category selling-unit metadata.');
$assert(str_contains($categoryHelper,'default_unit_type'),'Storefront category reads must expose the configured default unit.');
$unitMigrationChecksum=hash_file('sha256',$root.'/database/migrations/2026-08-27-category-default-unit-type.sql');
$assert(is_string($unitMigrationChecksum)&&str_contains($schema,$unitMigrationChecksum),'Fresh schema must baseline the category default-unit migration checksum.');
$assert(str_contains($categoryAdmin,'name="default_unit_type"')&&str_contains($categoryService,'default_unit_type'),'Category administration must expose and persist required selling units.');
$assert(str_contains($cron,"'categories' => ['uses_variant_size', 'default_unit_type']")&&str_contains($cron,"'2026-08-27-category-default-unit-type.sql'"),'Cron readiness must require the category unit metadata migration.');
foreach(['product_code','amazon_asin','selling_price','mrp','quantity','size_type','return_exchange_condition','pickup_address_code','customisation_id','associated_pixel','attr_brand_name','attr_printing_type','attr_eco_friendly','attr_fabric'] as $catalogField)$assert(str_contains($editorForm,$catalogField),'Catalogue editor field missing: '.$catalogField);
$assert(str_contains($editorForm,'name="meter_options"')&&str_contains($editorForm,'placeholder="10, 20, 30"'),'Meter products must expose configurable customer length options.');
$assert(CartService::parse_meter_options('10, 20, 30',1.0)===[10.0,20.0,30.0],'Meter length options must accept values such as 10, 20, and 30.');
$assert(str_contains($adminScript,'dataset.defaultUnitType')&&str_contains($adminScript,'data-meter-unit-field'),'Admin JavaScript must enforce category units and toggle meter-only fields.');
foreach(['low_stock_threshold_units','wash_care','seo_title','seo_description','dispatch_time','moq','lead_time'] as $legacyField)$assert(!str_contains($editorForm,'name="'.$legacyField.'"'),'Legacy editor field is still visible: '.$legacyField);
if($fail){foreach($fail as $message)fwrite(STDERR,"FAIL: $message\n");exit(1);}echo "admin_product_editor_v2_contract_test: OK\n";
