CREATE TABLE IF NOT EXISTS payment_attempts (
    id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id           INT DEFAULT NULL,
    payment_id         INT DEFAULT NULL,
    provider           VARCHAR(32)  NOT NULL,
    attempt_ref        VARCHAR(191) NOT NULL,
    status             VARCHAR(40)  NOT NULL DEFAULT 'created',
    source             VARCHAR(40)  NOT NULL DEFAULT 'create',
    gateway_payment_id VARCHAR(191) DEFAULT NULL,
    gateway_signature  VARCHAR(255) DEFAULT NULL,
    error_code         VARCHAR(80)  DEFAULT NULL,
    error_message      TEXT,
    webhook_event_id   VARCHAR(191) DEFAULT NULL,
    webhook_signature  VARCHAR(255) DEFAULT NULL,
    payload_json       LONGTEXT,
    retry_count        INT NOT NULL DEFAULT 0,
    first_seen_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_payment_attempt_provider_ref (provider, attempt_ref),
    INDEX idx_payment_attempt_order_id (order_id),
    INDEX idx_payment_attempt_payment_id (payment_id),
    INDEX idx_payment_attempt_status (status),
    INDEX idx_payment_attempt_webhook_event (webhook_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
