CREATE TABLE IF NOT EXISTS cod_confirmations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    channel ENUM('auto','whatsapp','call') NOT NULL DEFAULT 'auto',
    status ENUM('pending','confirmed','cancelled','auto_cancelled') NOT NULL DEFAULT 'pending',
    deadline_at DATETIME DEFAULT NULL,
    attempts INT NOT NULL DEFAULT 0,
    response_token CHAR(32) DEFAULT NULL,
    message_provider VARCHAR(40) DEFAULT NULL,
    message_id VARCHAR(191) DEFAULT NULL,
    message_status VARCHAR(40) DEFAULT 'queued',
    message_error TEXT,
    message_sent_at DATETIME DEFAULT NULL,
    message_attempts INT NOT NULL DEFAULT 0,
    last_inbound_message_id VARCHAR(191) DEFAULT NULL,
    last_inbound_text TEXT,
    last_inbound_at DATETIME DEFAULT NULL,
    notes TEXT,
    confirmed_at DATETIME DEFAULT NULL,
    cancelled_at DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_cod_confirmations_order_id (order_id),
    UNIQUE KEY uq_cod_confirmations_response_token (response_token),
    INDEX idx_cod_confirmations_status_deadline (status, deadline_at),
    INDEX idx_cod_confirmations_message_status (message_status, message_attempts),
    CONSTRAINT fk_cod_confirmations_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
