CREATE TABLE IF NOT EXISTS shiprocket_tracking_events (
    id                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id               INT DEFAULT NULL,
    shipment_id            INT DEFAULT NULL,
    source                 VARCHAR(32) NOT NULL DEFAULT 'webhook',
    external_event_id      VARCHAR(191) DEFAULT NULL,
    shiprocket_order_id    VARCHAR(64) DEFAULT NULL,
    shiprocket_shipment_id VARCHAR(64) DEFAULT NULL,
    awb_code               VARCHAR(255) DEFAULT NULL,
    status                 VARCHAR(80) DEFAULT NULL,
    courier_name           VARCHAR(255) DEFAULT NULL,
    tracking_url           VARCHAR(500) DEFAULT NULL,
    payload_json           LONGTEXT,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_shiprocket_tracking_events_order_id (order_id),
    INDEX idx_shiprocket_tracking_events_shipment_id (shipment_id),
    INDEX idx_shiprocket_tracking_events_awb_code (awb_code),
    INDEX idx_shiprocket_tracking_events_status (status),
    INDEX idx_shiprocket_tracking_events_event_id (external_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
