CREATE TABLE IF NOT EXISTS shipping_quotes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    quote_token CHAR(32) NOT NULL UNIQUE,
    customer_id INT DEFAULT NULL,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    country VARCHAR(120) NOT NULL,
    pincode VARCHAR(20) DEFAULT NULL,
    payment_method VARCHAR(32) NOT NULL,
    base_shipping DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    cod_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    shipping_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    source VARCHAR(32) NOT NULL DEFAULT 'manual',
    courier_name VARCHAR(255) DEFAULT NULL,
    courier_id INT DEFAULT NULL,
    expires_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_shipping_quotes_customer_expires (customer_id, expires_at),
    INDEX idx_shipping_quotes_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
