<?php
/**
 * Example credentials/config map.
 * Copy to config/app-config.php and fill with real values on each environment.
 * Do not commit config/app-config.php with secrets.
 */
return [
    'local' => [
        'APP_ENV' => 'local',
        'APP_URL' => 'http://localhost:8000',

        'DB_HOST' => '127.0.0.1',
        'DB_PORT' => '3306',
        'DB_USER' => 'root',
        'DB_PASSWORD' => '',
        'DB_NAME' => 'fabric_export',

        'ADMIN_NOTIFICATION_EMAIL' => 'you@example.com',
        'CRON_RUN_TOKEN' => 'replace-with-local-random-cron-token',
        'MAIL_FROM' => 'you@example.com',
        'SMTP_HOST' => 'smtp.example.com',
        'SMTP_PORT' => '587',
        'SMTP_PASSWORD' => 'replace-with-local-smtp-password',

        'RAZORPAY_KEY_ID' => 'rzp_test_xxxxxxxxxx',
        'RAZORPAY_KEY_SECRET' => 'replace-with-test-secret',
        'RAZORPAY_WEBHOOK_SECRET' => 'replace-with-test-webhook-secret',
        'COD_GUARD_WHATSAPP_THRESHOLD' => '1000',
        'COD_GUARD_CALL_THRESHOLD' => '2000',
        'COD_GUARD_CONFIRMATION_HOURS' => '24',
        'COD_GUARD_MESSAGE_MAX_ATTEMPTS' => '3',
        'COD_GUARD_WHATSAPP_PROVIDER' => 'whatsapp_cloud',
        'COD_GUARD_WHATSAPP_API_BASE_URL' => 'https://graph.facebook.com/v21.0',
        'COD_GUARD_WHATSAPP_PHONE_NUMBER_ID' => '',
        'COD_GUARD_WHATSAPP_ACCESS_TOKEN' => '',
        'COD_GUARD_WHATSAPP_TEMPLATE_NAME' => '',
        'COD_GUARD_WHATSAPP_TEMPLATE_LANGUAGE' => 'en',
        'COD_GUARD_WHATSAPP_APP_SECRET' => '',
        'COD_GUARD_WEBHOOK_VERIFY_TOKEN' => 'replace-with-random-verify-token',
        'COD_GUARD_WEBHOOK_TOKEN' => 'replace-with-random-post-token',
        'UTM_COOKIE_DAYS' => '30',
        'META_PIXEL_ID' => 'replace-with-meta-pixel-id',
        'META_CAPI_PIXEL_ID' => 'optional-override-pixel-id',
        'META_CAPI_ACCESS_TOKEN' => 'replace-with-meta-capi-access-token',
        'META_CAPI_TEST_EVENT_CODE' => 'optional-test-event-code',
        'ABANDONED_CART_EMAIL_ENABLED' => '1',
        'ABANDONED_CART_EMAIL_DELAY_MINUTES' => '60',
        'ABANDONED_CART_EMAIL_MAX_EMAILS' => '1',
        'PRODUCT_FEED_ENABLED' => '1',
        'PRODUCT_FEED_BASE_PATH' => '/feeds',
        'PRODUCT_FEED_XML_FILE' => 'products.xml',
        'PRODUCT_FEED_JSON_FILE' => 'products.json',
        'IMAGE_UPLOAD_MAX_MB' => '5',
        'IMAGE_MIN_WIDTH' => '600',
        'IMAGE_MIN_HEIGHT' => '800',
        'IMAGE_WEBP_QUALITY' => '82',
        'IMAGE_MAX_WIDTH' => '1920',
        'IMAGE_RESPONSIVE_WIDTHS' => '360,720,1200',
        'IMAGE_THUMB_WIDTH' => '360',
        'IMAGE_THUMB_HEIGHT' => '360',
        'INVENTORY_ALERT_ENABLED' => '1',
        'INVENTORY_ALERT_PIECE_THRESHOLD' => '5',
        'INVENTORY_ALERT_METER_THRESHOLD' => '10',
        'INVENTORY_ALERT_COOLDOWN_HOURS' => '24',
        'SHIPPING_RTO_RISK_ENABLED' => '1',
        'SHIPPING_RTO_RISK_HIGH_THRESHOLD' => '70',
        'SHIPPING_RTO_RISK_MEDIUM_THRESHOLD' => '40',
        'REVIEW_RATING_ENABLED' => '1',
        'REVIEW_RATING_AUTO_APPROVE' => '1',
        'REVIEW_RATING_MIN_LENGTH' => '10',
        'REVIEW_RATING_MAX_LENGTH' => '800',
        'ORDER_TIMELINE_ENABLED' => '1',
        'ORDER_TIMELINE_SHOW_INTERNAL_TO_ADMIN' => '1',

        'SHIPROCKET_ENABLED' => '0',
        'SHIPROCKET_BASE_URL' => 'https://apiv2.shiprocket.in',
        'SHIPROCKET_EMAIL' => 'ops@example.com',
        'SHIPROCKET_PASSWORD' => 'replace-with-shiprocket-password',
        'SHIPROCKET_WEBHOOK_SECRET' => 'replace-with-shiprocket-webhook-secret',
        'SHIPROCKET_PICKUP_LOCATION' => 'Primary',
        'SHIPROCKET_PICKUP_PINCODE' => '110001',
        'SHIPROCKET_DEFAULT_WEIGHT_KG' => '0.5',
        'SHIPROCKET_DEFAULT_REVERSE_WEIGHT_KG' => '0.5',
        'SHIPROCKET_DEFAULT_LENGTH_CM' => '20',
        'SHIPROCKET_DEFAULT_BREADTH_CM' => '20',
        'SHIPROCKET_DEFAULT_HEIGHT_CM' => '2',
        'SHIPROCKET_TRACKING_URL_BASE' => 'https://shiprocket.co/tracking/',
    ],

    'production' => [
        'APP_ENV' => 'production',
        'APP_URL' => 'https://yourdomain.com',

        'DB_HOST' => 'db-host-from-provider',
        'DB_PORT' => '3306',
        'DB_USER' => 'db-username',
        'DB_PASSWORD' => 'replace-with-production-db-password',
        'DB_NAME' => 'db-name',

        'ADMIN_NOTIFICATION_EMAIL' => 'ops@yourdomain.com',
        'CRON_RUN_TOKEN' => 'replace-with-production-random-cron-token',
        'MAIL_FROM' => 'noreply@yourdomain.com',
        'SMTP_HOST' => 'smtp.provider.com',
        'SMTP_PORT' => '587',
        'SMTP_PASSWORD' => 'replace-with-production-smtp-password',

        'RAZORPAY_KEY_ID' => 'rzp_live_xxxxxxxxxx',
        'RAZORPAY_KEY_SECRET' => 'replace-with-live-secret',
        'RAZORPAY_WEBHOOK_SECRET' => 'replace-with-live-webhook-secret',
        'COD_GUARD_WHATSAPP_THRESHOLD' => '1000',
        'COD_GUARD_CALL_THRESHOLD' => '2000',
        'COD_GUARD_CONFIRMATION_HOURS' => '24',
        'COD_GUARD_MESSAGE_MAX_ATTEMPTS' => '3',
        'COD_GUARD_WHATSAPP_PROVIDER' => 'whatsapp_cloud',
        'COD_GUARD_WHATSAPP_API_BASE_URL' => 'https://graph.facebook.com/v21.0',
        'COD_GUARD_WHATSAPP_PHONE_NUMBER_ID' => '',
        'COD_GUARD_WHATSAPP_ACCESS_TOKEN' => '',
        'COD_GUARD_WHATSAPP_TEMPLATE_NAME' => '',
        'COD_GUARD_WHATSAPP_TEMPLATE_LANGUAGE' => 'en',
        'COD_GUARD_WHATSAPP_APP_SECRET' => '',
        'COD_GUARD_WEBHOOK_VERIFY_TOKEN' => 'replace-with-random-verify-token',
        'COD_GUARD_WEBHOOK_TOKEN' => 'replace-with-random-post-token',
        'UTM_COOKIE_DAYS' => '30',
        'META_PIXEL_ID' => 'replace-with-meta-pixel-id',
        'META_CAPI_PIXEL_ID' => 'optional-override-pixel-id',
        'META_CAPI_ACCESS_TOKEN' => 'replace-with-meta-capi-access-token',
        'META_CAPI_TEST_EVENT_CODE' => 'optional-test-event-code',
        'ABANDONED_CART_EMAIL_ENABLED' => '1',
        'ABANDONED_CART_EMAIL_DELAY_MINUTES' => '60',
        'ABANDONED_CART_EMAIL_MAX_EMAILS' => '1',
        'PRODUCT_FEED_ENABLED' => '1',
        'PRODUCT_FEED_BASE_PATH' => '/feeds',
        'PRODUCT_FEED_XML_FILE' => 'products.xml',
        'PRODUCT_FEED_JSON_FILE' => 'products.json',
        'IMAGE_UPLOAD_MAX_MB' => '5',
        'IMAGE_MIN_WIDTH' => '600',
        'IMAGE_MIN_HEIGHT' => '800',
        'IMAGE_WEBP_QUALITY' => '82',
        'IMAGE_MAX_WIDTH' => '1920',
        'IMAGE_RESPONSIVE_WIDTHS' => '360,720,1200',
        'IMAGE_THUMB_WIDTH' => '360',
        'IMAGE_THUMB_HEIGHT' => '360',
        'INVENTORY_ALERT_ENABLED' => '1',
        'INVENTORY_ALERT_PIECE_THRESHOLD' => '5',
        'INVENTORY_ALERT_METER_THRESHOLD' => '10',
        'INVENTORY_ALERT_COOLDOWN_HOURS' => '24',
        'SHIPPING_RTO_RISK_ENABLED' => '1',
        'SHIPPING_RTO_RISK_HIGH_THRESHOLD' => '70',
        'SHIPPING_RTO_RISK_MEDIUM_THRESHOLD' => '40',
        'REVIEW_RATING_ENABLED' => '1',
        'REVIEW_RATING_AUTO_APPROVE' => '1',
        'REVIEW_RATING_MIN_LENGTH' => '10',
        'REVIEW_RATING_MAX_LENGTH' => '800',
        'ORDER_TIMELINE_ENABLED' => '1',
        'ORDER_TIMELINE_SHOW_INTERNAL_TO_ADMIN' => '1',

        'SHIPROCKET_ENABLED' => '0',
        'SHIPROCKET_BASE_URL' => 'https://apiv2.shiprocket.in',
        'SHIPROCKET_EMAIL' => 'ops@yourdomain.com',
        'SHIPROCKET_PASSWORD' => 'replace-with-live-shiprocket-password',
        'SHIPROCKET_WEBHOOK_SECRET' => 'replace-with-live-shiprocket-webhook-secret',
        'SHIPROCKET_PICKUP_LOCATION' => 'Primary',
        'SHIPROCKET_PICKUP_PINCODE' => '110001',
        'SHIPROCKET_DEFAULT_WEIGHT_KG' => '0.5',
        'SHIPROCKET_DEFAULT_REVERSE_WEIGHT_KG' => '0.5',
        'SHIPROCKET_DEFAULT_LENGTH_CM' => '20',
        'SHIPROCKET_DEFAULT_BREADTH_CM' => '20',
        'SHIPROCKET_DEFAULT_HEIGHT_CM' => '2',
        'SHIPROCKET_TRACKING_URL_BASE' => 'https://shiprocket.co/tracking/',
    ],
];
