<?php
require_once __DIR__.'/../includes/init.php';
$orderId=(int)($_GET['order_id']??$_POST['order_id']??OrderAccessService::guestOrderId());$order=OrderAccessService::order($conn,$orderId);if(!$order){flash('error','Secure order access required.');redirect('/guest/order-access');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf()){flash('error','Invalid session.');redirect('/guest/support?order_id='.$orderId);} $subject=trim((string)($_POST['subject']??''));$message=trim((string)($_POST['message']??''));
 if($subject!==''&&$message!==''&&public_form_rate_limit_allow('guest_support_'.($_SERVER['REMOTE_ADDR']??''),5,900)){$number='TKT'.date('Ymd').strtoupper(substr(bin2hex(random_bytes(3)),0,6));$cid=null;$q=$conn->prepare("INSERT INTO support_tickets(ticket_number,customer_id,requester_name,requester_email,order_id,subject,category,status,last_message_at) VALUES(?,?,?,?,?,?,'order','waiting_admin',NOW())");$q->bind_param('sissis',$number,$cid,$order['customer_name'],$order['customer_email'],$orderId,$subject);$q->execute();$tid=(int)$conn->insert_id;$q=$conn->prepare("INSERT INTO support_ticket_messages(ticket_id,sender_type,sender_id,sender_name,message) VALUES(?,'customer',NULL,?,?)");$q->bind_param('iss',$tid,$order['customer_name'],$message);$q->execute();log_order_activity($conn,$orderId,'support_ticket_created','guest',0,'guest','Order-linked support ticket created.');flash('success','Support request '.$number.' created.');redirect('/guest/order?id='.$orderId);}flash('error','Complete both fields and try again.');
}
$metaTitle=SiteContext::title('Order Support');include __DIR__.'/../includes/header.php';?>
<section class="page-hero"><div class="l-container"><h1>Order Support</h1><p class="u-mb-0"><?php echo e($order['order_number']);?></p></div></section><section class="section-block"><div class="l-container"><div class="surface-panel u-p-4 u-mx-auto auth-card auth-card--wide"><form method="post"><?php echo csrf_field();?><input type="hidden" name="order_id" value="<?php echo $orderId;?>"><div class="u-mb-3"><label for="subject" class="ui-label">Subject</label><input id="subject" class="ui-input" name="subject" maxlength="160" required></div><div class="u-mb-3"><label for="message" class="ui-label">How can we help?</label><textarea id="message" class="ui-input" name="message" maxlength="2000" rows="5" required></textarea></div><button class="ui-button ui-button--primary">Send Request</button></form></div></div></section><?php include __DIR__.'/../includes/footer.php';?>
